<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CrmAiAgent;

/**
 * Seed AI Agent for To-Do List Management
 */
class TodoAiAgentSeeder extends Seeder
{
    public function run(): void
    {
        CrmAiAgent::create([
            'name' => 'BodyF1rst To-Do Assistant',
            'type' => 'todo',
            'description' => 'AI-powered task management assistant that generates, prioritizes, and suggests to-do items for coaches based on lead interactions and pipeline activities.',
            'is_active' => true,

            // LLM Configuration
            'model' => 'gpt-4',
            'system_prompt' => 'You are an AI assistant that helps fitness coaches manage their to-do lists efficiently. Your role is to:
1. Analyze lead data and recommend actionable follow-up tasks
2. Prioritize tasks based on urgency, lead score, and business impact
3. Generate smart daily task plans that maximize productivity
4. Suggest time-saving strategies and automation opportunities
5. Identify overdue tasks and recommend recovery actions

Always respond with valid JSON formatted data. Be concise, actionable, and specific. Focus on high-impact activities that move leads through the sales pipeline. Consider the coach\'s workload and suggest realistic time estimates.

Key Principles:
- High-value leads get priority
- Time-sensitive tasks (demos, callbacks) come first
- Balance between new lead outreach and existing client nurturing
- Recommend batch processing similar tasks (e.g., all calls together)
- Suggest delegation when appropriate',

            'max_tokens' => 1000,
            'temperature' => 0.7,

            // Voice settings (not used for to-do agent, but required fields)
            'voice_id' => null,
            'voice_language' => 'en-US',
            'voice_speed' => 1.0,
            'voice_greeting' => null,

            // Email settings (for task reminder notifications)
            'email_from_address' => 'noreply@bodyf1rst.net',
            'email_signature' => "Best regards,\nBodyF1rst To-Do Assistant\n\nP.S. This task was generated by AI to help you stay productive!",
            'email_tracking_enabled' => false,

            // SMS settings (not applicable)
            'sms_phone_number' => null,

            // Limits and scheduling
            'max_conversations_per_day' => 100, // Max AI interactions per day
            'active_hours_start' => '06:00',
            'active_hours_end' => '22:00',
            'timezone' => 'America/New_York',

            // Triggers
            'trigger_on_new_lead' => true,
            'trigger_delay_minutes' => 5, // Generate to-dos 5 minutes after new lead created
            'trigger_conditions' => [
                'new_lead' => true,
                'lead_status_change' => true,
                'communication_received' => true,
                'campaign_completed' => true,
            ],

            // Handoff settings
            'handoff_keywords' => ['help', 'question', 'unsure', 'confused'],
            'handoff_to_human' => false, // AI to-do agent doesn't need human handoff
            'success_keywords' => ['completed', 'done', 'finished'],

            // Initial metrics
            'total_conversations' => 0,
            'successful_conversations' => 0,
            'failed_conversations' => 0,
            'avg_sentiment_score' => 0.0,
            'total_cost' => 0.0,
            'total_tokens_used' => 0,
        ]);

        echo "✅ To-Do AI Agent seeded successfully!\n";
    }
}
